name = "SeqFold"
uuid = "b3b2a78d-ef5a-44e0-bc1e-af93888afa44"
authors = ["phlaster <phlaster@users.noreply.github.com>"]
version = "0.0.1"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Printf = "1.11.0"
TOML = "1.0.3"
julia = "1.10"
